### PR TITLE
implemented hdist, hlon, hlat, true anomaly

### PR DESCRIPTION
**Pull request by mommermi**
added heliocentric distance, longitude, and latitude, as well as true anomaly, to `pyoorb.oorb_ephemeris` array output

Results checked by integrating zero steps: hlon==Omega+argper, heldist==q, true_anom==0

### CODE REVIEW

**Comment by mommermi** [comment]
Thanks, Lynne!
I saw that you already updated `sims_movingObjects.ooephemerides.py`, too. Are both updates already available on epyc?

**Comment by rhiannonlynne** [comment]
I’ll update epyc tomorrow :)

**Comment by rhiannonlynne** [comment]
epyc is updated :)

**Comment by rhiannonlynne** [comment]
I am curious though -- how do I sync up this PR with the changes in the root of oorb? I haven't checked, but I will assume you made the same changes in a PR there .. except I see the docs and other things are different. 
So when I pull from upstream (oorb:oorb), things will be different. And I would normally make a PR back to oorb with updates here that are not LSST-specific. Obviously I can't quite do that either. 

Let's come up with a plan to keep development in sync.

**Comment by mkelley** [comment]
Would rebasing be the right apporach?  I think that would take the latest at oorb/oorb and apply any local modifications on top of it.

**Comment by rhiannonlynne** [comment]
it wouldn’t really work in this case, I think, because the changes to open:open are more recent and involve files we have never modified. Plus we want to send changes back upstream when they’re generally useful.

**Comment by rhiannonlynne** [comment]
But mostly I think all this requires is a knowledge of this approach. In general, I suspect Michael will simply make contributions to oorb:orb as he’s mostly interested in adapting the non last specific pieces, so it will be fine. (As long as we get synced up).

**Comment by mommermi** [comment]
Right, my changes to lsst/oorb were only meant to enable the use of hlon, hlat, hdist, and the true anomaly in sims_movingObjects. All future changes will be done to oorb/oorb.

I looked a bit more into how to select output parameters in `pyoorb.oorb_ephemeris` - this time together with somebody who actually understands Fortran...

My current idea is the following:
* people build a boolean mask in form of an array that turns individual output parameters on and off: `param=[True, False, False, True...]` where, e.g., the first element refers to RA, the second to DEC...; there are n elements in total for n potential output parameters
* `param` is provided as input to `pyoorb.oorb_ephemeris` 
* `pyoorb.oorb_ephemeris`, generates an array of n output parameters for each object and epoch; only those parameters that are not masked are actually populated, the rest is set to zero

This approach is not ideal, as it produces a sparse array that eats up a lot of memory. However, we can cull the spare parts later in a python wrapper. Unfortunately, we cannot have `pyoorb.oorb_ephemeris` produce a shorter output array dynamically as it is 3 dimensional and the memory structure would be too complicated. 

Lynne, I would like to hear your opinion if this is something you could live with. If not, we could simply provide a second ephemeris generator tailored to the needs of LSST.

**Comment by rhiannonlynne** [comment]
Hmm. When they're set to 0, they're still taking up memory, as you point
out.
I'm having some issues currently with sims_movingObjects, after adding the
extra columns for hlon/hlat/hdist/True anomaly, and I'd like to make sure
they're not memory related somehow before committing to adding more
columns. I mean .. they shouldn't be, because it's not that much extra, but
something's gone wonky.

Culling out the spare parts later in a python wrapper is not ideal, because
as you say - the memory has already been used.

What I'd suggest is that you make two library methods -- one is
oorb_ephemeris and one is oorb_ephemeris_short .. the short one would have
just the minimal set of columns, while the long one would have everything.
If you want something in between, you have to go with the big set of
columns, but that's what it is.   (so .. pretty much, your second opinion,
except I don't think I'd say "tailored to the needs of LSST" only, I'd aim
for a set of columns that are useful for people doing bigger ephemeris
generation problems, and the people with smaller requirements could use the
longer ephemeris call).

**Comment by mommermi** [comment]
Sounds good, will do!

**Pull request merged**
